version: "3.7"

services:

    flask:
        image: bilges/clinvap_api_flask
        # build: ./flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=MyFlaskApp
            - FLASK_ENV=development
        expose:
            - 8080
        volumes:
            - clinvap_uploads:/app/app/static/input/uploads
            - clinvap_downloads:/app/app/static/output/downloads

    nginx:
        image: bilges/clinvap_api_nginx
        # build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"

    nextflow:
        image: bilges/clinvap_api_nextflow
        # build: ./nextflow
        container_name: nextflow
        volumes:
            - ./work:/nextflow_pipeline/work
            - clinvap_uploads:/nextflow_pipeline/uploads
            - clinvap_downloads:/nextflow_pipeline/downloads
        depends_on:
            - flask
            - nginx
volumes:
    clinvap_uploads:
    clinvap_downloads:
