name: api_app
channels:
  - anaconda
  - conda-forge
  - https://conda.anaconda.org/openeye
  - anaconda-fusion
  - defaults
dependencies:
  - argh=0.26.2
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - click=7.1.1
  - flask=1.1.1
  - icu=64.2
  - itsdangerous=1.1.0
  - jansson=2.11
  - jinja2=2.11.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - ncurses=6.2
  - openssl=1.1.1
  - pathtools=0.1.2
  - pcre=8.43
  - pip=20.0.2
  - python=3.6.10
  - python_abi=3.6
  - pyyaml=5.1.2
  - readline=8.0
  - setuptools=46.1.3
  - sqlite=3.31.1
  - tk=8.6.8
  - uwsgi=2.0.18
  - watchdog=0.10.2
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.1.7
  - zlib=1.2.11


